// frontend/src/components/properties/CustomK8sResourceProperties.vue
<template>
  <div class="flex flex-col w-full h-full items-center">
    <div class="grow w-full">
      <div class="text-3xl text-center font-bold mt-5">Custom Resource</div>
      <div class="p-10">
        <div class="mt-3">
          <div class="border-t-2 border-stone-500 text-xl mt-10 mb-3 flex pt-2 mb-5">
            <div>
              Properties
            </div>
            <div v-if="valuesAreNotSaved" class="ml-2">
              <Button @click="onUpdate" :disabled="!isFormValid"
                      class="p-button-rounded p-button-sm p-button-success updateButton">
                Update
              </Button>
            </div>
          </div>
          <div class="flex flex-col mb-2">
            <div class="mr-1">Name:</div>
            <div class="">
              <InputText class="w-full p-inputtext-sm" v-model="name"></InputText>
            </div>
          </div>
          <div class="flex flex-col mb-2">
            <div class="mr-1">Content:</div>
            <div class="">
              <TextArea class="w-full p-inputtext-sm font-mono" v-model="content" rows="10"></TextArea>
            </div>
          </div>
        </div>
        <div class="mt-10 flex flex-col items-center">
          <div class="flex justify-center items-center">
            <Button v-if="isNew" :disabled="!isFormValid" @click="onUpdate" icon="pi pi-save"
                    class="p-button-rounded p-button-primary p-button-lg largeButton" title="Save">
            </Button>

            <div v-if="!isNew">
              <Button @click="onDelete" icon="pi pi-trash"
                      class="p-button-rounded p-button-danger p-button-outlined"></Button>
            </div>
          </div>

        </div>

      </div>
    </div>


    <div class="pb-10">
      <Button @click="onClose"
              icon="pi pi-times"
              class="p-button-rounded p-button-primary p-button-outlined" title="Close"></Button>
    </div>
  </div>
</template>
<script lang="ts" setup>
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import TextArea from "primevue/textarea";
import {usePropertiesPanelStore} from "@/stores/propertiesPanelStore";
import {computed, onMounted, ref} from "vue";
import type {k4p} from "@wails/models";
import {useProjectStore} from "@/stores/projectStore";

const propertiesPanelStore = usePropertiesPanelStore();
const projectStore = useProjectStore();

const ckr = ref<k4p.CustomK8sResource>({} as k4p.CustomK8sResource);

propertiesPanelStore.$subscribe(fillProperties);

onMounted(() => {
  fillProperties();
});

function fillProperties() {
  const resFromStore = projectStore.customK8SResources.find(e => e.name === propertiesPanelStore.propertiesId);
  if (resFromStore) {
    ckr.value = resFromStore;
  } else {
    ckr.value = {} as k4p.CustomK8sResource;
  }
  name.value = ckr.value.name || "";
  content.value = ckr.value.content || ""
}

const name = ref<string>("");
const content = ref<string>("");

const isFormValid = computed((): boolean => {
  return name.value.trim().length > 0 && content.value.trim().length > 0;
});

const valuesAreNotSaved = computed((): boolean => {
  const resource = projectStore.customK8SResources.find(e => e.name === ckr.value.name);
  if (!resource) {
    return false
  }
  return resource.name !== name.value || resource.content !== content.value;
});

const onUpdate = function (): void {
  const ckrToSave: k4p.CustomK8sResource = {
    name: name.value,
    content: content.value
  };
  if (isNew.value) {
    projectStore.addCustomK8SResources(ckrToSave);
  } else {
    projectStore.updateCustomK8SResources(ckr.value, ckrToSave);
  }
  propertiesPanelStore.selectPanel("CustomK8sResourceProperties", name.value);
}

const onClose = function (): void {
  propertiesPanelStore.deselect();
}
const onDelete = function (): void {
  projectStore.deleteCustomK8SResources(ckr.value.name);
  propertiesPanelStore.deselect();
}
const isNew = computed((): boolean => {
  return !projectStore.customK8SResources.find(e => e.name === ckr.value.name);
});
</script>
<style>

</style>

// frontend/src/views/ClusterWizard/Steps/Apps/Sections/Properties/CustomK8sResourceProperties.tsx
import React, { useState } from 'react';
import { Button } from "primereact/button";
import { InputText } from "primereact/inputtext";
import { InputTextarea } from "primereact/inputtextarea";
import uiPropertiesPanelStore from "@/store/uiPropertiesPanelStore";
import { useFormik } from "formik";
import projectStore from "@/store/projectStore";
import { LogError } from "@wails-runtime/runtime";
import FormError from "@/components/FormError";
import * as Yup from "yup"
import { useOnFirstMount } from "@/reactHooks";
import { observer } from "mobx-react-lite";

const schema = Yup.object({
    name: Yup.string().required(),
    content: Yup.string().required()
})

const CustomK8SResourceProperties = () => {
    const [initialValues, setInitialValues] = useState({
            name: "",
            content: ""
        })
    useOnFirstMount(async () => {
        const resFromStore = projectStore.customK8SResources.find(e => e.name === uiPropertiesPanelStore.selectedPropertiesId);
        if (resFromStore) {
            setInitialValues(resFromStore)
        }
    })
    const formik = useFormik({
        enableReinitialize: true,
        validateOnMount: true,
        initialValues: initialValues,
        validationSchema: schema,
        onSubmit: (values, formikHelpers) => {
            if (uiPropertiesPanelStore.selectedPropertiesId) {
                projectStore.updateCustomK8SResources(uiPropertiesPanelStore.selectedPropertiesId, values);
            } else {
                projectStore.addCustomK8SResources(values)
            }
            uiPropertiesPanelStore.hidePanel()
        }
    })
    const onDelete = () => {
        if (uiPropertiesPanelStore.selectedPropertiesId) {
            projectStore.deleteCustomK8SResources(uiPropertiesPanelStore.selectedPropertiesId);
            uiPropertiesPanelStore.hidePanel()
        } else {
            LogError("Kubernetes resource is not selected")
        }
    }
    return <>
        <div className="flex flex-col w-full h-full items-center">

            <div className="grow w-full">
                <form onSubmit={formik.handleSubmit}>
                    <div className="text-3xl text-center font-bold mt-5">Custom Resource</div>
                    <div className="p-10">

                        <div className="flex flex-col mb-2">
                            <div className="mr-1 required">Name:</div>
                            <div className="">
                                <InputText
                                    name="name"
                                    value={formik.values.name}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    className="w-full p-inputtext-sm"></InputText>
                                <FormError error={formik.errors.name} touched={formik.touched.name}/>
                            </div>
                        </div>
                        <div className="flex flex-col mb-2">
                            <div className="mr-1 required">Content:</div>
                            <div className="">
                                <InputTextarea
                                    name="content"
                                    value={formik.values.content}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    className="w-full p-inputtext-sm font-mono"/>
                                <FormError error={formik.errors.content} touched={formik.touched.content}/>
                            </div>
                        </div>
                    </div>
                    <div className="mt-10 flex flex-col items-center">
                        <div className="flex justify-center items-center">
                            <div className="mr-5">
                                <Button disabled={!formik.isValid} type="submit" label="SAVE"
                                        className="p-button-primary"/>
                            </div>
                            {uiPropertiesPanelStore.selectedPropertiesId &&
                                <Button onClick={onDelete} label="Delete"
                                        className="p-button-raised p-button-danger p-button-text"/>}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </>
};

export default observer(CustomK8SResourceProperties);
