// frontend/src/components/Block.vue
<template>
  <div
      @mouseover="hover=true"
      @mouseout="hover=false"
      @click="$emit('select')"
      class="mt-5 p-5 bg-stone-800 rounded-xl border-2"
      :class="blockBorder">
    <div v-if="title" class="text-xl text-center font-bold">
      <span :class="{'text-stone-500': notActive}">{{ title }}</span>
    </div>
    <div v-if="$slots.default">
      <slot></slot>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {computed, ref} from "vue";

const props = defineProps<{
  title?: string
  selected?: boolean
  notActive?: boolean
}>();

defineEmits<{
  (e: 'select'): void
}>();


const hover = ref<boolean>(false);

const blockBorder = computed(() => {
  return ({
    'selectedBlock': props.selected,
    'hoveredBlock': hover.value && !props.selected,
    'defaultBlock': !hover.value && !props.selected,
  })
})
</script>

<style>
.selectedBlock {
  border-color: rgb(59 130 246);
}

.hoveredBlock {
  border-color: #78716C;
}

.defaultBlock {
  border-color: #292524;
}
</style>

// frontend/src/components/Block.tsx
import React, { useState } from "react";
import "./Block.css"

type BlockProps = {
    title?: string
    children?: React.ReactNode
    className?: string
    notActive?: boolean
    selected?: boolean
    onClick?: () => void
}

const Block = (props: BlockProps) => {
    const [hover, setHover] = useState(false)
    const blockBorder = () => {
        let cssClassNames: string[] = []
        if (props.selected) {
            cssClassNames.push("selectedBlock")
        }
        if (hover && !props.selected) {
            cssClassNames.push("hoveredBlock")
        }
        if (!hover && !props.selected) {
            cssClassNames.push("defaultBlock")
        }
        return cssClassNames.join(" ")
    }

    return <div
        onMouseOver={() => setHover(true)}
        onMouseOut={() => setHover(false)}
        onClick={props.onClick}
        className={`block-container p-3 rounded-xl border-2 cursor-pointer ${blockBorder()} ${props.className}`}>
        {
            props.title &&
            <div className="text-center font-bold">
                <span className={`${props.notActive?"text-stone-500":""}`}>{props.title}</span>
            </div>
        }
        <div className="flex items-center">{props.children}</div>
    </div>
}

export default Block
