// frontend/src/components/properties/OpenebsProperties.vue
<template>
  <div class="flex flex-col w-full h-full items-center">
    <div class="grow">
      <div class="text-3xl text-center font-bold mt-5">OpenEBS</div>
      <div class="p-10">
        <div>
          OpenEBS, is the most widely deployed and easy to use open-source storage solution for Kubernetes
        </div>
        <div class="mt-10 flex flex-col items-center">
          <div class="flex justify-center">
            <div class="mr-2">
              <FeatureSwitch feature-name="openebs">
              </FeatureSwitch>
            </div>
          </div>

        </div>
      </div>
    </div>


    <div class="pb-10">
      <Button @click="onClose"
              icon="pi pi-times"
              class="p-button-rounded p-button-primary p-button-outlined" title="Close"></Button>
    </div>
  </div>
</template>
<script lang="ts" setup>
import Button from "primevue/button";
import {usePropertiesPanelStore} from "@/stores/propertiesPanelStore";
import FeatureSwitch from "@/components/FeatureSwitch.vue";

const propertiesPanelStore = usePropertiesPanelStore();


const onClose = function (): void {
  propertiesPanelStore.deselect();
}


</script>
<style>

</style>

// frontend/src/views/ClusterWizard/Steps/ClusterPlanner/Sections/Properties/OpenEbsProperties.tsx
import React from 'react';
import AddonSwitch from "@/views/ClusterWizard/Steps/ClusterPlanner/Sections/Properties/components/AddonSwitch";

const OpenEbsProperties = () => {
    return (
        <div className="flex flex-col w-full h-full items-center">
            <div className="grow w-full">
                <div className="text-3xl text-center font-bold mt-5 flex items-center justify-center">
                    <span className="mr-2">OpenEBS</span>
                    <AddonSwitch name="openebs"/>
                </div>
                <div className="p-5">
                    OpenEBS, is the most widely deployed and easy to use open-source storage solution for Kubernetes.
                </div>

            </div>
        </div>
    );
};

export default OpenEbsProperties;
