// frontend/src/views/ProjectView.vue
<template>
  <main class="p-5 flex flex-col items-center justify-center h-full">
    <div class="w-full max-w-[400px]">
      <div class="text-9xl">K<span class="text-blue-500">4</span>Prox</div>
      <div>Kubernetes Manager for Proxmox</div>
    </div>
    <div></div>
    <div class="mt-14 w-full max-w-[400px] flex justify-center">
      <Block :not-active="generatingProject || openingProject" @click="newProject"
             class="mr-10 flex justify-center items-center w-[200px] h-[200px]">
        <div v-if="!generatingProject" class="flex flex-col items-center justify-center">
          <i class="pi pi-file text-stone-400" style="font-size: 5rem"></i>
          <span class="mt-5 text-center">Generate Project</span>
        </div>
        <div v-if="generatingProject" class="flex flex-col items-center justify-center">
          <ProgressSpinner/>
          <span class="mt-5 text-center">Generating project...</span>
        </div>
      </Block>
      <Block :not-active="generatingProject || openingProject" @click="openProject"
             class="flex justify-center items-center w-[200px] h-[200px]">
        <div v-if="!openingProject" class="flex flex-col items-center justify-center">
          <i class="pi pi-folder-open text-stone-400" style="font-size: 5rem"></i>
          <span class="mt-5 text-center">Open Project</span>
        </div>

        <div v-if="openingProject" class="flex flex-col items-center justify-center">
          <ProgressSpinner/>
          <span class="mt-5 text-center">Open Project</span>
        </div>
      </Block>
    </div>

  </main>
</template>
<script setup lang="ts">
import Block from "@/components/Block.vue";
import { useRouter } from "vue-router";
import { OpenProjectDialog, SaveProjectDialog } from "@wails/project/Service";
import { ref } from "vue";
import ProgressSpinner from 'primevue/progressspinner';
import { showError } from "@/utils/errors";
import { useDialog } from "primevue/usedialog";

const router = useRouter();
const generatingProject = ref(false)
const openingProject = ref(false)
const dialog = useDialog();

const newProject = async function () {
  if (generatingProject.value || openingProject.value) {
    return
  }
  try {
    generatingProject.value = true;
    const isProjectGenerated = await SaveProjectDialog();
    if (isProjectGenerated) {
      await router.push({name: "planner"})
    }
    generatingProject.value = false;
  } catch (err) {
    generatingProject.value = false;
    showError(dialog, err)
  }
}

const openProject = async function () {
  if (generatingProject.value || openingProject.value) {
    return
  }
  try {
    openingProject.value = true;
    const clusterIsAlreadyCreated = await OpenProjectDialog();
    if (clusterIsAlreadyCreated) {
      await router.push({name: "summary"})
    } else {
      await router.push({name: "planner"})
    }
  } catch (err) {
    openingProject.value = false;
    showError(dialog, err)
  }
}

</script>

// frontend/src/views/ProjectView.tsx
import { ProgressSpinner } from "primereact/progressspinner";
import React, { useState } from "react";
import Block from "../components/Block";
import { OpenProjectDialog, SaveProjectDialog } from "@wails/project/Service";
import { useNavigate } from "react-router-dom";
import { LogError } from "../../wailsjs/runtime";
import LogoContainer from "@/components/LogoContainer";

const ProjectView = () => {
    const navigate = useNavigate()
    const [wizardProjectInProgress, setWizardProjectInProgress] = useState(false)
    const [generatingProjectInProgress, setGeneratingProjectInProgress] = useState(false)
    const [openingProjectInProgress, setOpeningProjectInProgress] = useState(false)

    const wizardProjectHandler = async () => {
        try {
            setWizardProjectInProgress(true)
            const isProjectGenerated = await SaveProjectDialog();
            if (isProjectGenerated) {
                navigate("/cluster-planner")
            }
        } catch (err: any) {
            LogError(err)
        } finally {
            setWizardProjectInProgress(false)
        }
    }

    const openProjectHandler = async () => {
        try {
            setOpeningProjectInProgress(true)
            const clusterIsAlreadyCreated = await OpenProjectDialog();
            if (clusterIsAlreadyCreated) {
                navigate("/cluster-is-ready")
            } else {
                navigate("/cluster-open-not-provisioned")
            }
        } catch (err: any) {
            LogError(err)
        } finally {
            setOpeningProjectInProgress(false)
        }
    }

    return <LogoContainer>

        <Block
            notActive={generatingProjectInProgress || openingProjectInProgress || wizardProjectInProgress}
            onClick={wizardProjectHandler}
            className="mr-10 flex justify-center items-center w-[200px] h-[200px] mb-5">

            {
                wizardProjectInProgress
                    ? <div className="flex flex-col items-center justify-center">
                        <ProgressSpinner strokeWidth="8" />
                        <span className="mt-5 text-center">Generating project...</span>
                    </div>
                    : <div className="flex flex-col items-center justify-center">
                        <i className="pi pi-compass text-stone-400" style={{fontSize: "5rem"}}></i>
                        <span className="mt-5 text-center">Cluster planner</span>
                    </div>
            }
        </Block>
        <Block
            notActive={generatingProjectInProgress || openingProjectInProgress || wizardProjectInProgress}
            onClick={openProjectHandler}
            className="flex justify-center items-center w-[200px] h-[200px]">

            {
                openingProjectInProgress
                    ? <div className="flex flex-col items-center justify-center">
                        <ProgressSpinner strokeWidth="8" />
                        <span className="mt-5 text-center">Open Project</span>
                    </div>
                    : <div className="flex flex-col items-center justify-center">
                        <i className="pi pi-folder-open text-stone-400" style={{fontSize: "5rem"}}></i>
                        <span className="mt-5 text-center">Open Project</span>
                    </div>
            }
        </Block>
    </LogoContainer>
}

export default ProjectView
